4 commit

diff --git a/cliffwall b/cliffwall
--- a/cliffwall
+++ b/cliffwall
@@ -27,41 +27,48 @@ if [ $(id -u) -ne 0 ]; then
         exit 1
 fi
 
-# check existence files:
-if [ ! -e "$conf_dir/start" ]; then
-	echo -e "[ERROR]: $conf_dir/start script\nNot exist"
-	exit 1
-elif [ ! -e "$conf_dir/start_types" ]; then
-	echo -e "[ERROR]: $conf_dir/start_types script\nNot exist"
-	exit 1
-elif [ ! -e "$conf_dir/stop" ]; then
-	echo -e "[ERROR]: $conf_dir/stop script\nNot exist"
-	exit 1
-elif [ ! -e "$conf_dir/block" ]; then
-	echo -e "[ERROR]: $conf_dir/block script\nNot exist"
-	exit 1
-elif [ ! -e "$conf_dir/iface.conf" ]; then
-	echo -e "[ERROR]: $path3\nThis file not exist"
-	exit 1
-fi
-
-# permission of execution value
-bool=0 # is true
-
-for n in {"$init_functions","$conf_dir/start","$conf_dir/start_types","$conf_dir/stop","$conf_dir/block"}                      
-do
-	if [ ! -x "$n" ]; then
-		bool=1 # is false
-		echo -e "\n [WARNING]: $n\n Permission denied."
-		echo -e " Is not correctly set the execute permission:"
+cliffwall_test(){
+	# check existence files:
+	if [ ! -e "$conf_dir/start" ]; then
+		echo -e "[ERROR]: $conf_dir/start script\nNot exist"
+		exit 1
+	elif [ ! -e "$conf_dir/start_types" ]; then
+		echo -e "[ERROR]: $conf_dir/start_types script\nNot exist"
+		exit 1
+	elif [ ! -e "$conf_dir/stop" ]; then
+		echo -e "[ERROR]: $conf_dir/stop script\nNot exist"
+		exit 1
+	elif [ ! -e "$conf_dir/block" ]; then
+		echo -e "[ERROR]: $conf_dir/block script\nNot exist"
+		exit 1
+	elif [ ! -e "$conf_dir/iface.conf" ]; then
+		echo -e "[ERROR]: $path3\nThis file not exist"
+		exit 1
 	fi
-done
+	
+	# permission of execution value
+	bool=0 # is true
 
-if [ $bool = 1 ]; then
-	exit 1
+	for n in {"$init_functions","$conf_dir/start","$conf_dir/start_types","$conf_dir/stop","$conf_dir/block"}                      
+	do
+		if [ ! -x "$n" ]; then
+			bool=1 # is false
+			echo -e "\n [WARNING]: $n\n Permission denied."
+			echo -e " Is not correctly set the execute permission:"
+		fi
+	done
+
+	if [ $bool = 1 ]; then
+		exit 1
+	fi
+}
+
+if [ "$1" == 'test' ]; then
+	cliffwall_test
+	exit 0
 fi
-
-# run daemon
-$init_functions $1
+# this run cliffwall-init-functions only because cliffwall-init 
+# daemon has calling by start the system only:
+$init_functions $1 
 
 exit 0
